version: '3'
services:
  web:
    build: .
    volumes:
      - .:/shitsucomi
    ports:
      - "3000:3000"
    command: sh -c 'rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0'
    tty: true
    stdin_open: true
    networks:
      - shitsucomi_network
    environment:
      MYSQL_HOST: db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - shitsucomi_network
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"

# volumes:
#   mysql-webapp-data:

networks:
  shitsucomi_network:
    external: true
